# Generated by Django 4.2.7 on 2023-11-24 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('mi', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=30)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('mi', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=30)),
                ('ssn', models.CharField(max_length=20, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=30)),
                ('occupation_class', models.CharField(max_length=50)),
                ('medical_history', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('doses_required', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDelivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_delivered', models.PositiveIntegerField()),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('dose_on_hold', models.PositiveIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.patient')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.timeslot')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('dose_given', models.PositiveIntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.patient')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.timeslot')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='NurseScheduling',
            fields=[
                ('scheduling_id', models.AutoField(primary_key=True, serialize=False)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.nurse')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='schedule',
            field=models.ManyToManyField(through='PatientApp.NurseScheduling', to='PatientApp.timeslot'),
        ),
    ]
