# Generated by Django 4.2.7 on 2023-11-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
