# Generated by Django 4.2.7 on 2023-11-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0002_alter_nurse_address_alter_nurse_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='quantity_in_repository',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
