# Generated by Django 4.2.7 on 2023-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0003_vaccine_quantity_in_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
